export const CORE_SCHEMA = 'core';

export enum ECoreTableName {
  Branches              = 'branches',
  Locations             = 'locations',
  Organizations         = 'organizations',
  OrgAddresses          = 'org_addresses',
  OrgMembers            = 'org_members',
  Stores                = 'stores',
  StoreMembers          = 'store_members',
  Users                 = 'users',
  UserProfiles          = 'user_profiles',
  UserAddresses         = 'user_addresses',
  Roles                 = 'roles',
  UserRoles             = 'user_roles',
  Permissions           = 'permissions',
  RolePermissions       = 'role_permissions',
  Categories            = 'categories',
  Products              = 'products',
  ProductImages         = 'product_images',
  ProductSuppliers      = 'product_suppliers',
  ProductVariants       = 'product_variants',
  StoreProductConfig    = 'store_product_config',
  Suppliers             = 'suppliers',
  Inventory             = 'inventory',
  StockMovements        = 'stock_movements',
  UnpublishedStock      = 'unpublished_stock',
  UnpublishedStockMovements = 'unpublished_stock_movements',
  StockEntries          = 'stock_entries',
  StockTransfers        = 'stock_transfers',
  StockTransferItems    = 'stock_transfer_items',
  StockTransferRequests = 'stock_transfer_requests',
  PurchaseOrders            = 'purchase_orders',
  PurchaseItems             = 'purchase_items',
  PurchaseItemAllocations   = 'purchase_item_allocations',
  Customers             = 'customers',
  Orders                = 'orders',
  OrderItems            = 'order_items',
  DiscountCoupons       = 'discount_coupons',
  Invoices              = 'invoices',
  Bills                 = 'bills',
  BillItems             = 'bill_items',
  CustomerCreditTransactions = 'customer_credit_transactions',
  CreditApprovalRequests     = 'credit_approval_requests',
  QuickCharges               = 'quick_charges',
  CustomerTypeRules          = 'customer_type_rules',
  CommissionPayables         = 'commission_payables',
  PaymentTransactions   = 'payment_transactions',
  Expenses              = 'expenses',
  ItemReturns           = 'item_returns',
  ReturnItems           = 'return_items',
  Notifications         = 'notifications',
  ActivityLogs          = 'activity_logs',
  OrgActivityLogs       = 'org_activity_logs',
  ReportGenerationLogs  = 'report_generation_logs',
  ProductLogs           = 'product_logs',
  Platforms             = 'platforms',
  PlatformConfigurations = 'platform_configurations',

  // ─── Reference / Lookup tables ───────────────────────────────────────────────
  Countries             = 'ref_countries',
  States                = 'ref_states',
  Cities                = 'ref_cities',
  Currencies            = 'ref_currencies',
  Languages             = 'ref_languages',

  // ─── Vehicle & Transportation ─────────────────────────────────────────────────
  Vehicles              = 'vehicles',
  VehicleTypes          = 'vehicle_types',
  VehicleBrands         = 'vehicle_brands',
  FuelTypes             = 'fuel_types',
  Drivers               = 'drivers',
  VehicleDriverAssignments = 'vehicle_driver_assignments',
  VehicleLocations      = 'vehicle_locations',
  Trips                 = 'trips',
  TripCheckpoints       = 'trip_checkpoints',
  TripGoods             = 'trip_goods',
  TripEvents            = 'trip_events',
  FuelTransactions      = 'fuel_transactions',
  Maintenance           = 'maintenance',
  MaintenanceTypes      = 'maintenance_types',
  MaintenanceParts      = 'maintenance_parts',
  VehicleExpenses       = 'vehicle_expenses',
  VehicleDocuments      = 'vehicle_documents',
  DriverDocuments       = 'driver_documents',
  VehicleInsurance      = 'vehicle_insurance',
  TransportationOrders  = 'transportation_orders',
  TransportationOrderItems = 'transportation_order_items',
  GpsDevices            = 'gps_devices',
  Alerts                = 'alerts',

  // ─── Communication ────────────────────────────────────────────────────────────
  EmailTemplates        = 'email_templates',

  // ─── Field App ───────────────────────────────────────────────────────────────
  TripStops             = 'trip_stops',
  UserDeviceTokens      = 'user_device_tokens',

  // ─── CI / Deploy verification ─────────────────────────────────────────────
  DeploymentChecks      = 'deployment_checks',
}
